/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as UstawieniaRouteImport } from './routes/ustawienia'
import { Route as CeleIndexRouteImport } from './routes/cele.index'
import { Route as CeleIdRouteImport } from './routes/cele.$id'
import { Route as CeleNowyRouteImport } from './routes/cele.nowy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const UstawieniaRoute = UstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => rootRouteImport,
} as any)
const CeleIndexRoute = CeleIndexRouteImport.update({
  id: '/cele/',
  path: '/cele/',
  getParentRoute: () => rootRouteImport,
} as any)
const CeleIdRoute = CeleIdRouteImport.update({
  id: '/cele/$id',
  path: '/cele/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CeleNowyRoute = CeleNowyRouteImport.update({
  id: '/cele/nowy',
  path: '/cele/nowy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/ustawienia': typeof UstawieniaRoute
  '/cele/$id': typeof CeleIdRoute
  '/cele/nowy': typeof CeleNowyRoute
  '/cele/': typeof CeleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/ustawienia': typeof UstawieniaRoute
  '/cele/$id': typeof CeleIdRoute
  '/cele/nowy': typeof CeleNowyRoute
  '/cele': typeof CeleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/ustawienia': typeof UstawieniaRoute
  '/cele/$id': typeof CeleIdRoute
  '/cele/nowy': typeof CeleNowyRoute
  '/cele/': typeof CeleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/historia' | '/ustawienia' | '/cele/$id' | '/cele/nowy' | '/cele/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historia' | '/ustawienia' | '/cele/$id' | '/cele/nowy' | '/cele'
  id:
    | '__root__'
    | '/'
    | '/historia'
    | '/ustawienia'
    | '/cele/$id'
    | '/cele/nowy'
    | '/cele/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriaRoute: typeof HistoriaRoute
  UstawieniaRoute: typeof UstawieniaRoute
  CeleIdRoute: typeof CeleIdRoute
  CeleNowyRoute: typeof CeleNowyRoute
  CeleIndexRoute: typeof CeleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ustawienia': {
      id: '/ustawienia'
      path: '/ustawienia'
      fullPath: '/ustawienia'
      preLoaderRoute: typeof UstawieniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cele/': {
      id: '/cele/'
      path: '/cele'
      fullPath: '/cele/'
      preLoaderRoute: typeof CeleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cele/$id': {
      id: '/cele/$id'
      path: '/cele/$id'
      fullPath: '/cele/$id'
      preLoaderRoute: typeof CeleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cele/nowy': {
      id: '/cele/nowy'
      path: '/cele/nowy'
      fullPath: '/cele/nowy'
      preLoaderRoute: typeof CeleNowyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriaRoute: HistoriaRoute,
  UstawieniaRoute: UstawieniaRoute,
  CeleIdRoute: CeleIdRoute,
  CeleNowyRoute: CeleNowyRoute,
  CeleIndexRoute: CeleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
